Incorporates the VerbosityPrinter class with the reports module, replacing all of the active print statements
Many sections of report now include progress bars or verbose iteration statuses that are controlled by the printer class.

Below is some example output from the Report Generation ipython notebook
  (when verbosity is set to 2 on the create_full_report_pdf() function):

   *** Generating tables ***
     Iter 00 of 16 :   Generating table: targetSpamTable
     Iter 01 of 16 :   Generating table: targetGatesTable
     [...] (Some output removed to keep the commit message shorter)
     Iter 15 of 16 :   Generating table: germListTable
     Iter 16 of 16 :   Generating table: progressTable
    *** Generating plots ***
    Chi2 plots (2):
     Iter 0 of 1 :   Generating figure: bestEstimateColorBoxPlot
     Iter 1 of 1 :   Generating figure: invertedBestEstimateColorBoxPlot
     [...]

    *** Merging into template file ***
    Latex file(s) successfully generated.  Attempting to compile with pdflatex...

  ERROR: pdflatex returned code 256. Check Example_reportB.log to see details

Here is the same function with a verbosity of one:

    *** Generating tables ***
     [##################################################] 100.0%
    *** Generating plots ***
    Chi2 plots (2):
     [##################################################] 100.0%

    *** Merging into template file ***
    Latex file(s) successfully generated.  Attempting to compile with pdflatex...

  ERROR: pdflatex returned code 256. Check Example_reportB.log to see details.txt

And with a verbosity of 0:

  ERROR: pdflatex returned code 256. Check Example_reportB.log to see details