Upgrades report generation to work with jinja2 version 3.0+
Fixes errors like:

AttributeError: module 'jinja2' has no attribute 'evalcontextfilter'

caused by changes to the jinja2 API when moving from version 2->3.
Note: this breaks compatibility with jinja2 vesion 2.x, so if you get
errors about jinja2 not having the attribute 'pass_eval_context' then
you just need to update jinja2.