Output of running after_success on my machine:
Note that I've deleted my local version of beta as not to confuse the script, but it works both with/without the local branch

lsaldyt@s1000706:~/pyGSTi/hooks/travis$ ./after_success
Travis CI Passed
Getting current branchname/SHA
Branches existing on Travis Server:   # These are just my local branches
  coverage
* develop
  gh-pages
  master

Branchname (or SHA) is develop
Getting the latest version of beta
Deleting local version, if it exists
error: branch 'beta' not found.
Fetching from origin
Recreating local branch
Branch beta set up to track remote branch beta from origin.
Switched to a new branch 'beta'
Done.
Getting SHA of merge-base (To view merge tree between develop and beta
Done. SHA was 0236a51f00e427c362850da05a60aefbc7105ce4
Creating merge-tree
Done:
merged
  result 100755 f72a31e137dce15c90b004e7a579cea85766e163 hooks/travis/after_success
  our    100755 04debc015483fb8442a5ab29e784c3d711a6a2be hooks/travis/after_success
@@ -7,7 +7,8 @@

Git diff (merge-tree, whatever) gets output HERE
[..]

Merge of develop into beta is possible, attempting...
Automatic merge went well; stopped before committing as requested
Merge command finished.
Staging files..
Committing..
1 files changed:
[beta 4a88e2b] Merged develop into beta, as there were no conflicts and travis tests passed
Commit finished
Pushing to origin/beta. If this fails, there shouldn't be any useful output, since it would contain my access token

Obviously this would be different if the PUSHKEY was set to the actual git token (it wouldn't even prompt for a password or get output to the screen)
Password for 'https://adfajdfl@github.com': Secure push failed

lsaldyt@s1000706:~/pyGSTi/hooks/travis$ git log
commit 4a88e2b6535c3c0c5d643f9e5ff67b1f9346d953
Merge: 0236a51 14f34b5
Author: LSaldyt <lucassaldyt@yahoo.com>
Date:   Fri Jul 29 07:43:28 2016 -0600

    Merged develop into beta, as there were no conflicts and travis tests passed

Note that the current PUSHKEY is set to my user, but it could easily be changed to show a different author making the commits