Fix ValueError in Drift Report generation caused by incorrect Plotly syntax
Hi PyGSTi team,
When I run `Drift Characterization` in `00-Protocols.ipynb` tutorial file
```
from pygsti.modelpacks import smq1Q_XY
exp_design = smq1Q_XY.create_gst_experiment_design(max_max_length=4)
pygsti.io.write_empty_protocol_data('tutorial_files/test_drift_dir', exp_design, clobber_ok=True)

# Simulate time dependent data (right now, this just uses a time-independent model so this is uninteresting)                                                       
datagen_model = smq1Q_XY.target_model().depolarize(op_noise=0.05, spam_noise=0.1)
datagen_model.sim = "map" # only map-type can generate time-dep data
                          # can also construct this as target_model(simulator="map") above
pygsti.io.fill_in_empty_dataset_with_fake_data('tutorial_files/test_drift_dir/data/dataset.txt',
                                               datagen_model, num_samples=10, seed=2020, times=range(10))

gst_data = pygsti.io.read_data_from_dir('tutorial_files/test_drift_dir')
stability_protocol = pygsti.protocols.StabilityAnalysis()
results = stability_protocol.run(gst_data)

report = pygsti.report.create_drift_report(results, title='Demo Drift Report')
report.write_html('tutorial_files/DemoDriftReport')
```
I get an error:
```
ValueError: dictionary update sequence element #0 has length 1; 2 is required
...
File .../pygsti/extras/drift/driftreport.py:348, in ProbTrajectoriesPlot._create
yaxis=dict(title=dict("Probability", font=dict(size=14)), range=ylim),
```
The issue is located in pygsti/extras/drift/driftreport.py. The dict() constructor for the y-axis title was passing the string "Probability" as a positional argument, which is not valid for dictionary construction. I hope my contribution is useful.