Adds 3 forgotten 'super().__init__()' calls, fixing unit test failures.
With the addition of MongoDB serialization, NicelySerializable.__init__()
(which just falls back to MongoSerializable.__init__()) actually does
something nontrivial -- it sets the object's ._dbcoordinates attribute.
Thus, failure to call this base-class __init__ can result in

AttributeError: '<classname>' object has no attribute '_dbcoordinates'

errors.  This was happening for both LayerRules subclasses and
LindbladCoefficientBlock, all of which needed 'super().__init__() added
to their __init__ methods.